steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']
    dir: 'Trip_Reservation/backend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'amazing-api'
      - '--source'
      - 'Trip_Reservation/backend'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'   
