steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/project-32e135b6-7021-46f3-97a/amazing-api',
      '.'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'amazing-api'
      - '--image'
      - 'gcr.io/project-32e135b6-7021-46f3-97a/amazing-api'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/project-32e135b6-7021-46f3-97a/amazing-api'   
