# 1. Load the variables into the Spring Environment first
spring.config.import=optional:file:.env

# 2. Use those variables
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}

# 3. Docker Compose Settings
spring.docker.compose.file=compose.yaml
spring.docker.compose.enabled=true
# Use 'active' to ensure Spring stays connected to the container it started
spring.docker.compose.lifecycle-management=start_only

app.cors.allowed-origins=${FRONTEND_URL}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.rollback-on-error=true
logging.level.liquibase=debug


app.security.password.min-length=12
app.security.password.require-special-chars=true

management.endpoints.web.exposure.include=refresh

spring.cloud.bootstrap.enabled=true

# Tell Spring to pass the env file to the docker command it runs
spring.docker.compose.skip.in-tests=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update



