# The URL uses the service name 'db' defined in your compose.yaml
# When running via IntelliJ, use 'localhost'
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Note: inside the URL, use localhost because IntelliJ is OUTSIDE the docker network
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}

# Driver and Hibernate settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Initialization (So your schema.sql runs)
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none


spring.docker.compose.lifecycle-management=start-only
spring.docker.compose.env.filenames=../secret.env